### ISSUE TITLE
Demo Checklist (SEO guide lines)

### ISSUE THREAD

**Issue by kochapas** [2tonepantone/barcsnap#94]
- [x] Title tag is set and exceeds 20 chars.
- [x] Favicon tag is set.
- [x] Open Graph meta tags are properly set.
- [x] 404 and 500 pages are customized.
- [x] og:image has the right dimensions (1200x630)
